### ISSUE TITLE
Article Helpfulness feature

### ISSUE THREAD

**Issue by asyung** [sexinfo/sexinfo#174]
Have button on the article that would grab and collect feedback on how helpful an article is. It would be helpful for the group to start getting more feedback on the questions and articles that are written (which pages are most popular and helpful in categories such as pregnancy, sex, etc). 

For each article, we are thinking of a thumbs up thumbs down button for a "How helpful was this article?"

Also a button for readers to provide feedback to a new email (bonus will track the specific article that the reader has clicked).

A way to gather/store data on these articles(?)

**Comment by peterlinlin** [comment]
https://www.drupal.org/project/rate

**Comment by Jeffrey711** [comment]
This module fits the needs of the feature. The only limitation is that there is no way to view aggregate voting results for every single article on one page. You can only view votes for one article at a time. The vote submissions are all stored in a single database table, so it should be fairly straightforward to create a page that pulls data from that table and displays voting results.

Here is an outline of tasks:

- [ ] Create a new page with path _/voting-results_ or something similar.
- [ ] Write PHP functions for this page that queries the database table for data.
- [ ] Display data in a dynamic table.
- [ ] Write functions that allow the table sorted by vote counts, searched, etc.

**Comment by Jeffrey711** [comment]
Found the functionality to display aggregate results in Structure > Views > top_content. These are the steps I performed for future reference:

1. Use the **Plus1** display.
2. Under _FIELDS_, delete the first item: **(author User: Name (Author)**, because including it results in a SQL error.
3. Under _RELATIONSHIPS_, click on **Content: Vote results** to modify it.
4. Make sure the following items are set:
- **Value type** = _Points_
- **Vote tag** = _No filtering_ or your defined tag
- **Aggregation function** = _Total score_
5. Click **Apply**.
6. Change **Path** to _article-helpfulness_.
7. Change **Title** to _Article Helpfulness Ratings_.
8. **Save**

**Comment by Jeffrey711** [comment]
We'll use this ticket to track changes that need to be made in the coming weeks.

**Comment by Jeffrey711** [comment]
- [ ] Link to _Ask the Sexperts_ webform after voting.
- [ ] Display total upvotes and downvotes on ratings page.

**Comment by Jeffrey711** [comment]
After voting, a message saying, "You voted {'up', 'down'}," appears. Change this to {'yes', 'no'}.

**Comment by Jeffrey711** [comment]
Fixed in commit 5e15774bf4b108abed0716ea9d42614b687bbcba
